import type { Metadata } from "next";
import { Hero } from "@/components/home/Hero";
import { FeaturedCollections } from "@/components/home/FeaturedCollections";
import {
  ProductHighlights,
  type ProductHighlightItem,
} from "@/components/home/ProductHighlights";
import { ValuePropositions } from "@/components/home/ValuePropositions";
import { JsonLd } from "@/components/seo/JsonLd";
import {
  buildWebSiteSchema,
  buildOrganizationSchema,
  buildBreadcrumbSchema,
  buildItemListSchema,
} from "@/lib/seo/structured-data";
import { getProducts } from "@/lib/shopify";

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "https://dalify.in";

export const metadata: Metadata = {
  title: "Dalify — Organic Spices, Grains & Pulses | Shop Online India",
  description:
    "Shop certified organic spices, whole grains, pulses & instant mixes at Dalify. " +
    "FSSAI-approved. Free shipping on orders above ₹499. Order now.",
  alternates: { canonical: SITE_URL },
  openGraph: {
    title: "Dalify — Organic Spices, Grains & Pulses | Shop Online India",
    description:
      "Shop certified organic spices, whole grains, pulses & instant mixes at Dalify. " +
      "FSSAI-approved. Free shipping on orders above ₹499. Order now.",
    url: SITE_URL,
    // OG image is auto-generated by opengraph-image.tsx in this directory
  },
  twitter: {
    card: "summary_large_image",
    title: "Dalify — Organic Spices, Grains & Pulses | Shop Online India",
    description:
      "Shop certified organic spices, whole grains, pulses & instant mixes at Dalify. " +
      "FSSAI-approved. Free shipping on orders above ₹499. Order now.",
    // Twitter image is auto-picked from opengraph-image.tsx
  },
};

export default async function HomePage() {
  let featuredProducts: ReadonlyArray<ProductHighlightItem> = [];

  try {
    const { products } = await getProducts({ first: 6 });
    featuredProducts = products.map((p) => ({
      title: p.title,
      handle: p.handle,
      price: p.priceRange.minVariantPrice.amount,
      currencyCode: p.priceRange.minVariantPrice.currencyCode,
      imageSrc: p.featuredImage?.url,
    }));
  } catch {
    // Shopify credentials not set — fall back to placeholder UI
  }

  const itemListSchema =
    featuredProducts.length > 0
      ? buildItemListSchema(
          featuredProducts.map((p) => ({
            name: p.title,
            url: `${SITE_URL}/products/${p.handle}`,
          })),
        )
      : null;

  return (
    <>
      <JsonLd data={buildWebSiteSchema()} />
      <JsonLd data={buildOrganizationSchema()} />
      <JsonLd
        data={buildBreadcrumbSchema([{ name: "Home", url: SITE_URL }])}
      />
      {itemListSchema && <JsonLd data={itemListSchema} />}
      <Hero />
      <FeaturedCollections />
      <ProductHighlights products={featuredProducts.length > 0 ? featuredProducts : undefined} />
      <ValuePropositions />
    </>
  );
}
